services:
  kizuna:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kizuna
    restart: unless-stopped
    init: true
    env_file:
      - .env
    environment:
      BOT_SQLITE_PATH: /app/var/bot.db
      BOT_CONFIG_FILE: /app/config/bot_config.json
      PLUGINS_DIR: /app/var/plugins
    volumes:
      - ./config:/app/config
      - ./var:/app/var
